(() => {
  const sheets=[...document.querySelectorAll('.care-sheet')];
  const careButtons=[...document.querySelectorAll('[data-care]')];
  const toyKinds=['home-tv','home-phone','home-read','home-music','home-shower','home-bed'];
  const actionClasses=['bubble-blow','play-jump','play-dance','play-sprint','play-skip','play-dodge','play-roll','bed-sleeping','home-read-face','home-phone-face','home-music-face'];
  const commandKinds=['cmd-highfive','cmd-peace','cmd-wave','cmd-hide-left','cmd-hide-right','cmd-dig'];
  const shadowKinds=['shadow-feed','shadow-bubble','shadow-jump','shadow-dance','shadow-sprint','shadow-skip','shadow-dodge','shadow-roll','shadow-highfive','shadow-peace','shadow-wave','shadow-hide-left','shadow-hide-right','shadow-dig','shadow-rest','shadow-bed'];
  let activeCare='',activityTimer=0,wakeTimer=0,commandTimer=0,shadowTimer=0;
  let timers=[];

  function injectStyles(){
    const style=document.createElement('style');
    style.textContent=`
      .care-sheet .care-grid{grid-template-columns:repeat(2,34px)}
      .mini-icon{display:grid;place-items:center;width:22px;height:22px;font-size:15px;line-height:1}
      .bubbles-mini{position:relative;width:22px;height:22px}.bubbles-mini:before,.bubbles-mini:after{content:"";position:absolute;border:2px solid #72b7ca;border-radius:50%}.bubbles-mini:before{width:12px;height:12px;left:1px;top:7px}.bubbles-mini:after{width:8px;height:8px;right:0;top:1px;box-shadow:-1px 13px 0 -2px rgba(114,183,202,.85)}
      .viewer-bubble{position:absolute;z-index:18;pointer-events:none;border:3px solid #72b7ca;border-radius:50%;background:rgba(220,248,255,.18);box-shadow:inset 3px 3px 0 rgba(255,255,255,.55),0 8px 16px rgba(74,130,148,.11);animation:bubbleTowardViewer 1.55s ease-out forwards}@keyframes bubbleTowardViewer{0%{opacity:0;transform:translate(-50%,-50%) scale(.18)}12%{opacity:1;transform:translate(-50%,-50%) scale(.35)}55%{opacity:1;transform:translate(calc(-50% + var(--bx)),calc(-50% - 18px)) scale(1.05)}86%{opacity:.82;transform:translate(calc(-50% + var(--bx2)),calc(-50% - 32px)) scale(1.8)}100%{opacity:0;transform:translate(calc(-50% + var(--bx2)),calc(-50% - 42px)) scale(2.25)}}
      .ground-puff{position:absolute;z-index:9;pointer-events:none;width:18px;height:7px;border-radius:50%;background:rgba(118,99,76,.2);animation:groundPuff .52s ease-out forwards}.ground-puff.soft{background:rgba(110,128,116,.16)}@keyframes groundPuff{0%{opacity:0;transform:translate(-50%,0) scale(.3)}25%{opacity:.9}100%{opacity:0;transform:translate(calc(-50% + var(--px)),-14px) scale(1.7,.72)}}
      .impact-flash{position:absolute;z-index:20;pointer-events:none;width:22px;height:22px;border:3px solid rgba(240,190,74,.9);border-radius:50%;animation:impactFlash .45s ease-out forwards}@keyframes impactFlash{0%{opacity:0;transform:translate(-50%,-50%) scale(.2)}30%{opacity:1}100%{opacity:0;transform:translate(-50%,-50%) scale(1.7)}}
      .phone-tap{position:absolute;right:7px;bottom:8px;width:8px;height:8px;border-radius:50%;background:#dff7ff;box-shadow:0 0 12px rgba(150,225,255,.9);animation:phoneTap .6s ease-out forwards}@keyframes phoneTap{0%,100%{opacity:0;transform:scale(.4)}35%{opacity:1;transform:scale(1.25)}}

      .slime.bubble-blow{animation:bubbleBody 6.2s ease-in-out both}.slime.bubble-blow .mouth{top:82px;width:18px;height:18px;border:3px solid #315247;border-radius:50%;background:rgba(255,255,255,.18)}@keyframes bubbleBody{0%,100%{transform:translate3d(var(--x),var(--y),0)}24%,56%{transform:translate3d(calc(var(--x) + 5px),calc(var(--y) - 2px),0) scale(.98,1.02)}40%,72%{transform:translate3d(calc(var(--x) - 4px),var(--y),0) scale(1.03,.98)}}
      .slime.play-jump{animation:playJump 4.7s cubic-bezier(.22,.74,.28,1) both}@keyframes playJump{0%,100%{transform:translate3d(var(--x),var(--y),0)}15%{transform:translate3d(calc(var(--x) - 48px),calc(var(--y) - 74px),0) rotate(-5deg)}23%{transform:translate3d(calc(var(--x) - 58px),var(--y),0) scale(1.15,.8)}31%{transform:translate3d(calc(var(--x) - 12px),calc(var(--y) - 94px),0) rotate(4deg)}40%{transform:translate3d(calc(var(--x) + 4px),var(--y),0) scale(1.17,.79)}49%{transform:translate3d(calc(var(--x) + 62px),calc(var(--y) - 82px),0) rotate(6deg)}58%{transform:translate3d(calc(var(--x) + 68px),var(--y),0) scale(1.16,.8)}68%{transform:translate3d(calc(var(--x) + 18px),calc(var(--y) - 105px),0) rotate(-4deg)}79%{transform:translate3d(var(--x),var(--y),0) scale(1.18,.78)}88%{transform:translate3d(calc(var(--x) - 16px),calc(var(--y) - 48px),0)}}
      .slime.play-dance{animation:playDance 3.3s ease-in-out both}@keyframes playDance{0%,100%{transform:translate3d(var(--x),var(--y),0)}12%{transform:translate3d(calc(var(--x) - 24px),calc(var(--y) - 18px),0) rotate(-10deg)}26%{transform:translate3d(calc(var(--x) + 24px),calc(var(--y) - 6px),0) rotate(10deg)}40%{transform:translate3d(calc(var(--x) - 20px),calc(var(--y) - 25px),0) rotate(-8deg)}54%{transform:translate3d(calc(var(--x) + 22px),calc(var(--y) - 8px),0) rotate(9deg)}68%{transform:translate3d(calc(var(--x) - 15px),calc(var(--y) - 20px),0) rotate(-7deg)}84%{transform:translate3d(calc(var(--x) + 12px),calc(var(--y) - 5px),0) rotate(6deg)}}
      .slime.play-sprint{animation:playSprint 3.2s cubic-bezier(.2,.8,.25,1) both}@keyframes playSprint{0%,100%{transform:translate3d(var(--x),var(--y),0)}8%{transform:translate3d(var(--x),calc(var(--y) + 7px),0) scale(1.14,.82)}24%{transform:translate3d(calc(var(--x) + 115px),var(--y),0) skewX(-8deg)}40%{transform:translate3d(calc(var(--x) - 105px),var(--y),0) skewX(8deg)}58%{transform:translate3d(calc(var(--x) + 120px),var(--y),0) skewX(-9deg)}76%{transform:translate3d(calc(var(--x) - 72px),var(--y),0) skewX(7deg)}90%{transform:translate3d(var(--x),var(--y),0) scale(1.12,.84)}}
      .slime.play-skip{animation:playSkip 4s ease-in-out both}@keyframes playSkip{0%,100%{transform:translate3d(var(--x),var(--y),0)}12%{transform:translate3d(calc(var(--x) - 52px),calc(var(--y) - 35px),0) rotate(-4deg)}24%{transform:translate3d(calc(var(--x) - 22px),var(--y),0) scale(1.08,.88)}38%{transform:translate3d(calc(var(--x) + 20px),calc(var(--y) - 42px),0) rotate(4deg)}52%{transform:translate3d(calc(var(--x) + 48px),var(--y),0) scale(1.08,.88)}67%{transform:translate3d(calc(var(--x) + 12px),calc(var(--y) - 38px),0) rotate(-3deg)}82%{transform:translate3d(calc(var(--x) - 25px),var(--y),0) scale(1.08,.88)}}
      .slime.play-dodge{animation:playDodge 3.6s cubic-bezier(.25,.8,.25,1) both}@keyframes playDodge{0%,100%{transform:translate3d(var(--x),var(--y),0)}16%{transform:translate3d(calc(var(--x) - 92px),var(--y),0) skewX(-8deg)}31%{transform:translate3d(calc(var(--x) + 14px),var(--y),0)}47%{transform:translate3d(calc(var(--x) + 96px),var(--y),0) skewX(8deg)}64%{transform:translate3d(calc(var(--x) - 18px),var(--y),0)}80%{transform:translate3d(calc(var(--x) - 68px),var(--y),0) skewX(-6deg)}92%{transform:translate3d(var(--x),var(--y),0)}}
      .slime.play-roll{animation:playRoll 4.6s linear both;transform-origin:50% 55%}@keyframes playRoll{0%{transform:translate3d(var(--x),var(--y),0) rotate(0deg) scale(1)}8%{transform:translate3d(var(--x),var(--y),0) rotate(0deg) scale(.96)}54%{transform:translate3d(var(--x),var(--y),0) rotate(360deg) scale(.96)}82%{transform:translate3d(var(--x),var(--y),0) rotate(720deg) scale(.93)}92%{transform:translate3d(var(--x),var(--y),0) rotate(732deg) scale(.98)}100%{transform:translate3d(var(--x),var(--y),0) rotate(720deg) scale(1)}}

      .toy.emoji-toy{display:block;margin:0;background:none;box-shadow:none;opacity:0;pointer-events:none;filter:drop-shadow(0 5px 5px rgba(44,69,57,.12))}.toy.emoji-toy.show{opacity:1}
      .toy.home-phone{left:50%;bottom:72px;width:42px;height:68px;z-index:6}.toy.home-phone:before{content:"";position:absolute;inset:0;border-radius:9px;background:#3f4e5c;border:4px solid #566674;box-shadow:0 8px 18px rgba(40,50,60,.18)}.toy.home-phone:after{content:"";position:absolute;left:6px;right:6px;top:7px;bottom:9px;border-radius:5px;background:linear-gradient(160deg,#bcecf3,#8dc3d8 55%,#d8c8ee)}.toy.home-phone.show{animation:propRight 5.8s ease both}
      .toy.home-read{left:50%;bottom:66px;width:96px;height:62px;z-index:6;transform-origin:50% 90%}.toy.home-read:before{content:"NEWS";position:absolute;left:-48px;top:3px;width:96px;height:56px;box-sizing:border-box;padding:7px 7px 0;border:3px solid #b7ad93;border-radius:4px;background:linear-gradient(#fbf8ec,#f0ead8);color:#4f514d;font:900 10px/1.05 Arial,sans-serif;letter-spacing:1.1px;text-align:left;box-shadow:0 7px 15px rgba(72,69,57,.13),inset 0 -1px 0 rgba(110,101,80,.15)}.toy.home-read:after{content:"";position:absolute;left:-39px;top:22px;width:78px;height:29px;background:linear-gradient(90deg,#91a09d 0 22px,transparent 22px 27px,#7b7d76 27px 48px,transparent 48px 53px,#7b7d76 53px 78px),repeating-linear-gradient(0deg,transparent 0 4px,rgba(92,92,84,.42) 4px 6px);opacity:.78}.toy.home-read.show{animation:newspaperRead 6s ease both}@keyframes newspaperRead{0%{opacity:0;transform:translateY(14px) rotate(0) scale(.76)}12%,38%{opacity:1;transform:translateY(0) rotate(-2deg) scale(1)}48%{transform:translateY(1px) rotate(2deg) scale(.98)}58%,88%{opacity:1;transform:translateY(0) rotate(-1deg) scale(1)}100%{opacity:0;transform:translateY(6px) rotate(0) scale(.9)}}
      .toy.home-music{left:50%;bottom:72px;width:36px;height:80px;z-index:7}.toy.home-music:before{content:"";position:absolute;left:2px;top:0;width:30px;height:30px;border-radius:50%;background:#596777;box-shadow:inset 0 0 0 5px #738496}.toy.home-music:after{content:"";position:absolute;left:14px;top:26px;width:8px;height:48px;border-radius:8px;background:#596777}.toy.home-music.show{animation:propRight 6.2s ease both}
      @keyframes propRight{0%{opacity:0;transform:translate(76px,10px) scale(.72)}12%,88%{opacity:1;transform:translate(44px,0) scale(1)}100%{opacity:0;transform:translate(44px,0) scale(.9)}}@keyframes propCenter{0%{opacity:0;transform:translateY(12px) scale(.72)}12%,88%{opacity:1;transform:translateY(0) scale(1)}100%{opacity:0;transform:translateY(5px) scale(.9)}}
      .slime.home-phone-face .eye,.slime.home-read-face .eye{height:8px;top:63px;box-shadow:none}.slime.home-music-face{animation:musicBob 6.2s ease-in-out both}.slime.home-music-face .mouth{top:82px;width:24px;height:21px;border:3px solid #315247;border-radius:50%;background:#f7b8c0}@keyframes musicBob{0%,100%{transform:translate3d(var(--x),var(--y),0)}18%,42%,66%{transform:translate3d(calc(var(--x) - 7px),calc(var(--y) - 5px),0) rotate(-3deg)}30%,54%,78%{transform:translate3d(calc(var(--x) + 7px),calc(var(--y) - 7px),0) rotate(3deg)}}
      .toy.home-bed.show{animation:bedStay 8.4s ease both!important}@keyframes bedStay{0%{opacity:0;transform:translateX(-80px) scale(.82)}8%,88%{opacity:1;transform:translateX(0) scale(1)}100%{opacity:0;transform:translateX(28px) scale(.94)}}.slime.bed-sleeping{animation:bedSleep 6.8s ease-in-out both}.slime.bed-sleeping .eye{height:4px;top:67px;border-radius:999px;box-shadow:none}@keyframes bedSleep{0%,100%{transform:translate3d(var(--x),var(--y),0)}20%,88%{transform:translate3d(var(--x),calc(var(--y) + 12px),0) scale(1.15,.76)}}

      .slime-shadow.shadow-feed{animation:shadowFeed 1.1s ease both}@keyframes shadowFeed{0%,100%{transform:translateX(var(--shadow-x,0px)) scaleX(var(--shadow-scale,1));opacity:var(--shadow-opacity,.9)}45%{transform:translateX(var(--shadow-x,0px)) scaleX(1.08);opacity:.82}}
      .slime-shadow.shadow-bubble{animation:shadowSettle 6.2s ease both}.slime-shadow.shadow-rest{animation:shadowSettle 6.2s ease both}@keyframes shadowSettle{0%,100%{transform:translateX(var(--shadow-x,0px)) scaleX(1);opacity:.9}20%,85%{transform:translateX(var(--shadow-x,0px)) scaleX(1.04);opacity:.82}}
      .slime-shadow.shadow-jump{animation:shadowJump 4.7s cubic-bezier(.22,.74,.28,1) both}@keyframes shadowJump{0%,100%{transform:translateX(var(--shadow-x,0px)) scaleX(1);opacity:.9}15%{transform:translateX(calc(var(--shadow-x,0px) - 48px)) scaleX(.62);opacity:.38}23%{transform:translateX(calc(var(--shadow-x,0px) - 58px)) scaleX(1.08);opacity:.9}31%{transform:translateX(calc(var(--shadow-x,0px) - 12px)) scaleX(.56);opacity:.3}40%{transform:translateX(calc(var(--shadow-x,0px) + 4px)) scaleX(1.1);opacity:.9}49%{transform:translateX(calc(var(--shadow-x,0px) + 62px)) scaleX(.6);opacity:.34}58%{transform:translateX(calc(var(--shadow-x,0px) + 68px)) scaleX(1.09);opacity:.9}68%{transform:translateX(calc(var(--shadow-x,0px) + 18px)) scaleX(.52);opacity:.26}79%{transform:translateX(var(--shadow-x,0px)) scaleX(1.12);opacity:.9}88%{transform:translateX(calc(var(--shadow-x,0px) - 16px)) scaleX(.76);opacity:.54}}
      .slime-shadow.shadow-dance{animation:shadowDance 3.3s ease-in-out both}@keyframes shadowDance{0%,100%{transform:translateX(var(--shadow-x,0px)) scaleX(1);opacity:.9}12%{transform:translateX(calc(var(--shadow-x,0px) - 24px)) scaleX(.78);opacity:.58}26%{transform:translateX(calc(var(--shadow-x,0px) + 24px)) scaleX(.9);opacity:.72}40%{transform:translateX(calc(var(--shadow-x,0px) - 20px)) scaleX(.72);opacity:.5}54%{transform:translateX(calc(var(--shadow-x,0px) + 22px)) scaleX(.88);opacity:.7}68%{transform:translateX(calc(var(--shadow-x,0px) - 15px)) scaleX(.75);opacity:.54}84%{transform:translateX(calc(var(--shadow-x,0px) + 12px)) scaleX(.92);opacity:.76}}
      .slime-shadow.shadow-sprint{animation:shadowSprint 3.2s cubic-bezier(.2,.8,.25,1) both}@keyframes shadowSprint{0%,100%{transform:translateX(var(--shadow-x,0px)) scaleX(1);opacity:.9}8%{transform:translateX(var(--shadow-x,0px)) scaleX(1.12);opacity:.9}24%{transform:translateX(calc(var(--shadow-x,0px) + 115px)) scaleX(.95);opacity:.8}40%{transform:translateX(calc(var(--shadow-x,0px) - 105px)) scaleX(.95);opacity:.8}58%{transform:translateX(calc(var(--shadow-x,0px) + 120px)) scaleX(.93);opacity:.78}76%{transform:translateX(calc(var(--shadow-x,0px) - 72px)) scaleX(.96);opacity:.82}90%{transform:translateX(var(--shadow-x,0px)) scaleX(1.1);opacity:.88}}
      .slime-shadow.shadow-skip{animation:shadowSkip 4s ease-in-out both}@keyframes shadowSkip{0%,100%{transform:translateX(var(--shadow-x,0px)) scaleX(1);opacity:.9}12%{transform:translateX(calc(var(--shadow-x,0px) - 52px)) scaleX(.72);opacity:.5}24%{transform:translateX(calc(var(--shadow-x,0px) - 22px)) scaleX(1.06);opacity:.9}38%{transform:translateX(calc(var(--shadow-x,0px) + 20px)) scaleX(.68);opacity:.46}52%{transform:translateX(calc(var(--shadow-x,0px) + 48px)) scaleX(1.06);opacity:.9}67%{transform:translateX(calc(var(--shadow-x,0px) + 12px)) scaleX(.7);opacity:.48}82%{transform:translateX(calc(var(--shadow-x,0px) - 25px)) scaleX(1.05);opacity:.88}}
      .slime-shadow.shadow-dodge{animation:shadowDodge 3.6s cubic-bezier(.25,.8,.25,1) both}@keyframes shadowDodge{0%,100%{transform:translateX(var(--shadow-x,0px)) scaleX(1);opacity:.9}16%{transform:translateX(calc(var(--shadow-x,0px) - 92px)) scaleX(.95);opacity:.82}31%{transform:translateX(calc(var(--shadow-x,0px) + 14px)) scaleX(1);opacity:.88}47%{transform:translateX(calc(var(--shadow-x,0px) + 96px)) scaleX(.95);opacity:.82}64%{transform:translateX(calc(var(--shadow-x,0px) - 18px)) scaleX(1);opacity:.88}80%{transform:translateX(calc(var(--shadow-x,0px) - 68px)) scaleX(.96);opacity:.84}92%{transform:translateX(var(--shadow-x,0px)) scaleX(1);opacity:.9}}
      .slime-shadow.shadow-roll{animation:shadowRoll 4.6s linear both}@keyframes shadowRoll{0%,100%{transform:translateX(var(--shadow-x,0px)) scaleX(1);opacity:.9}8%,54%{transform:translateX(var(--shadow-x,0px)) scaleX(.95);opacity:.82}82%{transform:translateX(var(--shadow-x,0px)) scaleX(.86);opacity:.68}92%{transform:translateX(var(--shadow-x,0px)) scaleX(1.04);opacity:.86}}
      .slime-shadow.shadow-highfive{animation:shadowHigh 1.8s ease both}@keyframes shadowHigh{0%,100%{transform:translateX(var(--shadow-x,0px)) scaleX(1);opacity:.9}50%{transform:translateX(var(--shadow-x,0px)) scaleX(.48);opacity:.24}}
      .slime-shadow.shadow-peace{animation:shadowPeace 2.1s ease both}@keyframes shadowPeace{0%,100%{transform:translateX(var(--shadow-x,0px)) scaleX(1);opacity:.9}25%{transform:translateX(calc(var(--shadow-x,0px) - 8px)) scaleX(.94);opacity:.82}55%{transform:translateX(calc(var(--shadow-x,0px) + 8px)) scaleX(.92);opacity:.8}80%{transform:translateX(var(--shadow-x,0px)) scaleX(.97);opacity:.86}}
      .slime-shadow.shadow-wave{animation:shadowWave 3s ease-in-out both}@keyframes shadowWave{0%,100%{transform:translateX(var(--shadow-x,0px)) scaleX(1);opacity:.9}18%{transform:translateX(calc(var(--shadow-x,0px) - 4px)) scaleX(.8);opacity:.68}38%{transform:translateX(calc(var(--shadow-x,0px) + 4px)) scaleX(.6);opacity:.48}56%{transform:translateX(calc(var(--shadow-x,0px) - 3px)) scaleX(.45);opacity:.32}70%{transform:translateX(calc(var(--shadow-x,0px) + 2px)) scaleX(.5);opacity:.36}84%{transform:translateX(var(--shadow-x,0px)) scaleX(.78);opacity:.64}}
      .slime-shadow.shadow-hide-left{animation:shadowHideLeft 3s ease both}@keyframes shadowHideLeft{0%,100%{transform:translateX(var(--shadow-x,0px)) scaleX(1);opacity:.9}25%,72%{transform:translateX(calc(var(--shadow-x,0px) - 185px)) scaleX(.9);opacity:.72}48%{transform:translateX(calc(var(--shadow-x,0px) - 168px)) scaleX(.92);opacity:.76}}
      .slime-shadow.shadow-hide-right{animation:shadowHideRight 3s ease both}@keyframes shadowHideRight{0%,100%{transform:translateX(var(--shadow-x,0px)) scaleX(1);opacity:.9}25%,72%{transform:translateX(calc(var(--shadow-x,0px) + 185px)) scaleX(.9);opacity:.72}48%{transform:translateX(calc(var(--shadow-x,0px) + 168px)) scaleX(.92);opacity:.76}}
      .slime-shadow.shadow-dig{animation:shadowDig 3s ease both}@keyframes shadowDig{0%,100%{transform:translateX(var(--shadow-x,0px)) scaleX(1);opacity:.9}24%{transform:translateX(var(--shadow-x,0px)) scaleX(1.08);opacity:.62}44%,70%{transform:translateX(var(--shadow-x,0px)) scaleX(.3);opacity:0}82%{transform:translateX(var(--shadow-x,0px)) scaleX(1.06);opacity:.56}}
      .slime-shadow.shadow-bed{animation:shadowBed 8.4s ease both}@keyframes shadowBed{0%,100%{transform:translateX(var(--shadow-x,0px)) scaleX(1);opacity:.9}20%,82%{transform:translateX(var(--shadow-x,0px)) scaleX(1.1);opacity:.05}}
      @media(max-width:420px){.care-sheet{width:84px}.care-sheet .care-grid{grid-template-columns:repeat(2,32px)}.care-option{width:32px;height:32px}}
    `;
    document.head.appendChild(style);
  }

  function menus(){
    const play=document.querySelector('#care-play .care-grid');
    if(play)play.innerHTML=`
      <button class="care-option" data-play="jump" title="Jump"><span class="mini-icon">⬆️</span><span>Jump</span></button>
      <button class="care-option" data-play="dance" title="Dance"><span class="mini-icon">💃</span><span>Dance</span></button>
      <button class="care-option" data-play="sprint" title="Sprint"><span class="mini-icon">💨</span><span>Sprint</span></button>
      <button class="care-option" data-play="skip" title="Skip"><span class="mini-icon">➰</span><span>Skip</span></button>
      <button class="care-option" data-play="dodge" title="Dodge"><span class="mini-icon">↔️</span><span>Dodge</span></button>
      <button class="care-option" data-play="roll" title="Roll"><span class="mini-icon">🌀</span><span>Roll</span></button>`;
    const interact=document.querySelector('#care-interact .care-grid');
    if(interact)interact.innerHTML=`
      <button class="care-option" data-interact="highfive" title="High five"><span>🖐️</span><span>High five</span></button>
      <button class="care-option" data-interact="peace" title="Peace"><span>✌️</span><span>Peace</span></button>
      <button class="care-option" data-interact="wave" title="Wave"><span>👋</span><span>Wave</span></button>
      <button class="care-option" data-interact="hide" title="Hide"><span>🙈</span><span>Hide</span></button>
      <button class="care-option" data-interact="dig" title="Dig"><span>⛏️</span><span>Dig</span></button>
      <button class="care-option" data-interact="bubble" title="Bubbles"><span class="bubbles-mini"></span><span>Bubbles</span></button>`;
    const home=document.querySelector('#care-home .care-grid');
    if(home)home.innerHTML=`
      <button class="care-option" data-home="tv" title="TV"><span>📺</span><span>TV</span></button>
      <button class="care-option" data-home="phone" title="Play phone"><span>📱</span><span>Play phone</span></button>
      <button class="care-option" data-home="read" title="Read"><span>📰</span><span>Read</span></button>
      <button class="care-option" data-home="music" title="Music"><span>🎤</span><span>Music</span></button>
      <button class="care-option" data-home="shower" title="Shower"><span>🚿</span><span>Shower</span></button>
      <button class="care-option" data-home="bed" title="Bed"><span>😴</span><span>Bed</span></button>`;
  }

  injectStyles();menus();

  function closeCare(){sheets.forEach(s=>s.classList.remove('open'));careButtons.forEach(b=>b.classList.remove('active'));activeCare=''}
  function openCare(name){if(activeCare===name){closeCare();return}closeCare();document.getElementById(`care-${name}`)?.classList.add('open');document.querySelector(`[data-care="${name}"]`)?.classList.add('active');activeCare=name;setSettingsOpen(false)}
  careButtons.forEach(b=>b.addEventListener('click',()=>openCare(b.dataset.care)));
  function selectOption(button){button.closest('.care-sheet')?.querySelectorAll('.care-option').forEach(i=>i.classList.remove('active'));button.classList.add('active')}
  function later(fn,ms){const t=window.setTimeout(fn,ms);timers.push(t);return t}
  function clearTimers(){timers.forEach(clearTimeout);timers=[];clearTimeout(activityTimer);clearTimeout(wakeTimer);clearTimeout(commandTimer);clearTimeout(shadowTimer)}
  function clearShadow(){els.shadow.classList.remove(...shadowKinds)}
  function shadow(kind,duration){clearShadow();void els.shadow.offsetWidth;els.shadow.classList.add(`shadow-${kind}`);shadowTimer=window.setTimeout(clearShadow,duration)}
  function clearAction(){els.slime.classList.remove(...actionClasses,...commandKinds);clearShadow()}
  function setToy(kind,duration){els.toy.className=`toy emoji-toy ${kind}`;els.toy.textContent='';void els.toy.offsetWidth;replayFx(els.toy,'show',duration)}
  function groundPuff(count=2,soft=false){const sr=els.stage.getBoundingClientRect(),r=els.slime.getBoundingClientRect(),cx=r.left-sr.left+r.width/2,cy=r.bottom-sr.top-4;for(let i=0;i<count;i++){const p=document.createElement('span');p.className=`ground-puff${soft?' soft':''}`;p.style.left=`${cx+(i-(count-1)/2)*10}px`;p.style.top=`${cy}px`;p.style.setProperty('--px',`${(Math.random()-.5)*24}px`);els.fx.appendChild(p);setTimeout(()=>p.remove(),650)}}
  function impact(){const sr=els.stage.getBoundingClientRect(),r=els.slime.getBoundingClientRect(),f=document.createElement('span');f.className='impact-flash';f.style.left=`${r.left-sr.left+r.width/2}px`;f.style.top=`${r.top-sr.top+r.height*.35}px`;els.fx.appendChild(f);setTimeout(()=>f.remove(),500)}
  function bubble(){const sr=els.stage.getBoundingClientRect(),r=els.slime.getBoundingClientRect(),b=document.createElement('span'),size=20+Math.round(Math.random()*10),drift=(Math.random()-.5)*28;b.className='viewer-bubble';b.style.width=b.style.height=`${size}px`;b.style.left=`${r.left-sr.left+r.width/2}px`;b.style.top=`${r.top-sr.top+r.height*.66}px`;b.style.setProperty('--bx',`${drift}px`);b.style.setProperty('--bx2',`${drift*1.5}px`);els.fx.appendChild(b);setTimeout(()=>b.remove(),1700)}
  function startAction(button,cls,duration,message,shadowKind=cls.replace('play-','')){clearTimers();clearAction();selectOption(button);stopThrow();clearReactionClasses();void els.slime.offsetWidth;els.slime.classList.add(cls);shadow(shadowKind,duration);commit(message);activityTimer=setTimeout(()=>{els.slime.classList.remove(cls);els.slime.classList.add('idle')},duration)}

  const foodInfo={'🍓':['strawberry','•','food-crumb'],'🍏':['green apple','●','apple-bit'],'🍪':['cookie','▪','cookie-bit'],'🍇':['grapes','●','grape-bit'],'🍉':['watermelon','◆','melon-bit'],'🥕':['carrot','▲','carrot-bit']};
  function eat(symbol,button){const info=foodInfo[symbol];if(state.fullness>=96){react('tap-react',420);commit(`${state.name} is already completely full.`);return}selectOption(button);els.food.textContent=symbol;state.fullness+=18;state.happiness+=3;replayFx(els.food,'show',1100);react('feed-react',1100);shadow('feed',1100);later(()=>particles(info[1],5,info[2]),620);commit(`Yum! ${state.name} munches the ${info[0]}.`)}
  document.querySelectorAll('[data-food]').forEach(b=>b.addEventListener('click',()=>eat(b.dataset.food,b)));

  document.querySelectorAll('[data-play]').forEach(button=>button.addEventListener('click',()=>{
    if(state.energy<10){react('rest-react',850);commit(`${state.name} is too sleepy to play right now.`);return}
    const kind=button.dataset.play;state.happiness+=kind==='sprint'?14:10;state.energy-=kind==='sprint'?10:7;state.fullness-=2;
    if(kind==='jump'){startAction(button,'play-jump',4700,`${state.name} jumps around the playground!`,'jump');[1080,1880,2780,3710,4470].forEach((d,i)=>later(()=>groundPuff(i===4?2:1,true),d))}
    else if(kind==='dance'){startAction(button,'play-dance',3300,`${state.name} dances happily!`,'dance');[450,1350,2350].forEach(d=>later(()=>particles('♪',1,'play-note'),d))}
    else if(kind==='sprint'){startAction(button,'play-sprint',3200,`${state.name} sprints across the playground!`,'sprint');[650,1250,1900,2550].forEach(d=>later(()=>groundPuff(2,true),d))}
    else if(kind==='skip'){startAction(button,'play-skip',4000,`${state.name} skips around in a steady rhythm!`,'skip');[850,1650,2450,3250].forEach(d=>later(()=>groundPuff(1,true),d))}
    else if(kind==='dodge'){startAction(button,'play-dodge',3600,`${state.name} dodges left and right!`,'dodge')}
    else if(kind==='roll'){startAction(button,'play-roll',4600,`${state.name} rolls and acts cute.`,'roll')}
  }));

  function command(button,cls,duration,message,effect='none'){clearTimers();clearAction();selectOption(button);stopThrow();clearReactionClasses();void els.slime.offsetWidth;els.slime.classList.add(cls);shadow(cls.replace('cmd-',''),duration);if(effect==='impact')later(impact,720);if(effect==='spark')later(()=>particles('✦',1,'command-peace'),420);if(effect==='dust'){later(()=>groundPuff(3),550);later(()=>groundPuff(2),1100);later(()=>groundPuff(2),2150)}commit(message);commandTimer=setTimeout(()=>{els.slime.classList.remove(cls);els.slime.classList.add('idle')},duration)}
  document.querySelectorAll('[data-interact]').forEach(button=>button.addEventListener('click',()=>{
    const kind=button.dataset.interact;state.happiness+=3;
    if(kind==='highfive')command(button,'cmd-highfive',1800,`${state.name} jumps toward you for a high five!`,'impact');
    else if(kind==='peace')command(button,'cmd-peace',2100,`${state.name} strikes a little peace pose.`,'spark');
    else if(kind==='wave')command(button,'cmd-wave',3000,`${state.name} waves while backing away, then comes back.`);
    else if(kind==='hide'){const side=Math.random()<.5?'cmd-hide-left':'cmd-hide-right';command(button,side,3000,`${state.name} hides at the side and peeks back at you.`)}
    else if(kind==='dig')command(button,'cmd-dig',3000,`${state.name} digs downward and peeks out from the ground.`,'dust');
    else if(kind==='bubble'){clearTimers();clearAction();selectOption(button);stopThrow();clearReactionClasses();els.slime.classList.add('bubble-blow');shadow('bubble',6200);[350,1250,2200,3200,4250,5250].forEach(d=>later(bubble,d));commit(`${state.name} blows bubbles toward you.`);activityTimer=setTimeout(()=>{els.slime.classList.remove('bubble-blow');els.slime.classList.add('idle')},6200)}
  }));

  function repeatParticles(symbol,count,cls,repeats,gap){for(let i=0;i<repeats;i++)later(()=>particles(symbol,count,cls),i*gap)}
  function homeBase(button,kind,duration,message){clearTimers();clearAction();selectOption(button);stopThrow();clearReactionClasses();setToy(kind,duration);shadow('rest',duration);commit(message)}
  function startTV(button){state.energy+=8;state.happiness+=5;state.fullness-=1;homeBase(button,'home-tv',5600,`${state.name} settles down beside the TV for a proper rest.`);react('pet-react',1200,'pet-face')}
  function startPhone(button){state.happiness+=7;state.energy-=2;homeBase(button,'home-phone',5800,`${state.name} settles in to play on the phone.`);els.slime.classList.add('home-phone-face');[900,1900,3000,4100].forEach(d=>later(()=>{const p=document.createElement('span');p.className='phone-tap';els.toy.appendChild(p);setTimeout(()=>p.remove(),650)},d));activityTimer=setTimeout(()=>{els.slime.classList.remove('home-phone-face');els.slime.classList.add('idle')},5800)}
  function startRead(button){state.energy+=4;state.happiness+=4;homeBase(button,'home-read',6000,`${state.name} settles down to read the newspaper.`);els.slime.classList.add('home-read-face');activityTimer=setTimeout(()=>{els.slime.classList.remove('home-read-face');els.slime.classList.add('idle')},6000)}
  function startMusic(button){state.happiness+=8;state.energy+=2;homeBase(button,'home-music',6200,`${state.name} listens for a moment, then starts singing along.`);later(()=>els.slime.classList.add('home-music-face'),1300);[1900,2850,3850,4800].forEach(d=>later(()=>particles('♪',1,'play-note'),d));activityTimer=setTimeout(()=>{els.slime.classList.remove('home-music-face');els.slime.classList.add('idle')},6200)}
  function startShower(button){state.energy+=5;state.happiness+=5;homeBase(button,'home-shower',4800,`${state.name} stands under the shower and gets properly rinsed.`);react('pet-react',1050,'pet-face');repeatParticles('|',4,'shower-drop',5,650)}
  function startBed(button){selectOption(button);if(state.energy>=97){react('tap-react',420);commit(`${state.name} is too awake for bed.`);return}clearTimers();clearAction();stopThrow();clearReactionClasses();state.energy+=22;state.fullness-=3;setToy('home-bed',8400);els.sleepFx.classList.add('long-rest');replayFx(els.sleepFx,'show',6800);els.slime.classList.add('bed-sleeping');shadow('bed',8400);commit(`${state.name} settles on top of the bed... zzz.`);wakeTimer=setTimeout(()=>{els.slime.classList.remove('bed-sleeping');els.slime.classList.add('idle');els.sleepFx.classList.remove('show','long-rest');render(`${state.name} wakes up feeling refreshed.`)},6800);activityTimer=setTimeout(()=>els.toy.classList.remove('show'),8400)}
  document.querySelectorAll('[data-home]').forEach(button=>button.addEventListener('click',()=>{const k=button.dataset.home;if(k==='tv')startTV(button);else if(k==='phone')startPhone(button);else if(k==='read')startRead(button);else if(k==='music')startMusic(button);else if(k==='shower')startShower(button);else if(k==='bed')startBed(button)}));
})();